### ISSUE TITLE
May I ask where you found the exercise link?

### ISSUE THREAD

**Issue by ckf104** [strongBrave/3d_computer_vision_Andreas_Geiger#1]
Hi, recently I also want to learn this 3DV lectures, but it seems to me that there are only lecture slides in [exercise link](https://drive.google.com/drive/folders/17YkOlItn9PycNb5bT_O4nVlavlX0_VKQ). May I ask where you found the exercise?

**Comment by strongBrave** [comment]
This exercise is attained through my teacher, so I did not know how to find the exercises online.
